# SwiftLint configuration for TorFramework

# Включенные директории
included:
  - Sources
  - Tests

# Исключенные директории
excluded:
  - build
  - output
  - sources
  - tor-0.4.8.19
  - tor-ios-fixed
  - .build
  - DerivedData

# Отключенные правила (для Objective-C wrapper совместимости)
disabled_rules:
  - todo
  - trailing_whitespace

# Opt-in правила
opt_in_rules:
  - empty_count
  - empty_string

# Настройки
line_length: 120
type_body_length: 300
file_length: 500

# Исключения
identifier_name:
  excluded:
    - id
    - ip
    - url
    - tor

